version: "3.1"
services:
  catamel:
    build: .
    hostname: catamelmoonshotdemo
    ports:
     - "443:443"
    secrets:
     - source: sp_key
  satosa:
    build: satosaconf
    volumes:
      - ./satosaconf/:/root/satosa/
    environment:
      DATA_DIR: /root/satosa
    ports:
     - "8000:8000"

  fakeduo:
    build: ./fake_duo

secrets:
  sp_key:
    file: ./secrets/sp/sp-key.pem
